---
title: "Article HW"
author: "Lauren VanValkenburg"
date: "2/28/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Table 4 to Table 6

```{r}
library(foreign)
library(stringr)
library(plyr)
library(reshape2)
source("xtable.r")

pew <- read.spss("pew.sav")
pew <- as.data.frame(pew)

religion <- pew[c("q16", "reltrad", "income")]
religion$reltrad <- as.character(religion$reltrad)
religion$reltrad <- str_replace(religion$reltrad, " Churches", "")
religion$reltrad <- str_replace(religion$reltrad, " Protestant", " Prot")
religion$reltrad[religion$q16 == " Atheist (do not believe in God) "] <- "Atheist"
religion$reltrad[religion$q16 == " Agnostic (not sure if there is a God) "] <- "Agnostic"
religion$reltrad <- str_trim(religion$reltrad)
religion$reltrad <- str_replace_all(religion$reltrad, " \\(.*?\\)", "")

religion$income <- c("Less than $10,000" = "<$10k", 
                     "10 to under $20,000" = "$10-20k", 
                     "20 to under $30,000" = "$20-30k", 
                     "30 to under $40,000" = "$30-40k", 
                     "40 to under $50,000" = "$40-50k", 
                     "50 to under $75,000" = "$50-75k",
                     "75 to under $100,000" = "$75-100k", 
                     "100 to under $150,000" = "$100-150k", 
                     "$150,000 or more" = ">150k", 
                     "Don't know/Refused (VOL)" = "Don't know/refused")[religion$income]

religion$income <- factor(religion$income, levels = c("<$10k", "$10-20k", "$20-30k", "$30-40k", "$40-50k", "$50-75k", 
                                                      "$75-100k", "$100-150k", ">150k", "Don't know/refused"))

table6 <- count(religion, c("reltrad", "income"))
names(table6)[1] <- "religion"

xtable(table6[1:10, ], file = "pew-clean.tex")
View(table6)

table4 <- dcast(table6, religion ~ income)
xtable(table4[1:10, 1:7], file = "pew-raw.tex")
View(table4)
```

## Table 7 to Table 8

```{r}
options(stringsAsFactors = FALSE)
library(lubridate)
library(reshape2)
library(stringr)
library(plyr)
source("xtable.r")

table7 <- read.csv("billboard.csv")
table7 <- table7[, c("year", "artist.inverted", "track", "time", "date.entered", "x1st.week", "x2nd.week", "x3rd.week", "x4th.week", "x5th.week", "x6th.week", "x7th.week", "x8th.week", "x9th.week", "x10th.week", "x11th.week", "x12th.week", "x13th.week", "x14th.week", "x15th.week", "x16th.week", "x17th.week", "x18th.week", "x19th.week", "x20th.week", "x21st.week", "x22nd.week", "x23rd.week", "x24th.week", "x25th.week", "x26th.week", "x27th.week", "x28th.week", "x29th.week", "x30th.week", "x31st.week", "x32nd.week", "x33rd.week", "x34th.week", "x35th.week", "x36th.week", "x37th.week", "x38th.week", "x39th.week", "x40th.week", "x41st.week", "x42nd.week", "x43rd.week", "x44th.week", "x45th.week", "x46th.week", "x47th.week", "x48th.week", "x49th.week", "x50th.week", "x51st.week", "x52nd.week", "x53rd.week", "x54th.week", "x55th.week", "x56th.week", "x57th.week", "x58th.week", "x59th.week", "x60th.week", "x61st.week", "x62nd.week", "x63rd.week", "x64th.week", "x65th.week", "x66th.week", "x67th.week", "x68th.week", "x69th.week", "x70th.week", "x71st.week", "x72nd.week", "x73rd.week", "x74th.week", "x75th.week", "x76th.week")]
names(table7)[2] <- "artist"

table7$artist <- iconv(table7$artist, "MAC", "ASCII//translit")
table7$track <- str_replace(table7$track, " \\(.*?\\)", "")
names(table7)[-(1:5)] <- str_c("wk", 1:76)
table7 <- arrange(table7, year, artist, track)

long_name <- nchar(table7$track) > 20
table7$track[long_name] <- paste0(substr(table7$track[long_name], 0, 20), "...")

xtable(table7[c(1:3, 6:10), 1:8], "billboard-raw.tex")

table8 <- melt(table7, id = 1:5, na.rm = T)
table8$week <- as.integer(str_replace_all(table8$variable, "[^0-9]+", ""))
table8$variable <- NULL

table8$date.entered <- ymd(table8$date.entered)
table8$date <- table8$date.entered + weeks(table8$week - 1)
table8$date.entered <- NULL
table8 <- rename(table8, c("value" = "rank"))
table8 <- arrange(table8, year, artist, track, time, week)
table8 <- table8[c("year", "artist", "time", "track", "date", "week", "rank")]

clean_out <- mutate(table8, 
                    date = as.character(date))
xtable(clean_out[1:15, ], "billboard-clean.tex")
View(table8)
```
